# This is a generic workfloww that can be used to scan
# content-and-tooling projects for vulnerabilities.
name: mend

on:
  workflow_call:

jobs:

  mend:
    runs-on: "ubuntu-latest"

    steps:
      # To access the mend secrets, we now need to trigger on pull_request_target event
      # which by default runs in the context of the main branch, so we use this to retrieve
      # the PR object and then checkout the merge commit sha
      - name: "Retrieve PR"
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest

      - name: "checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 1
          # If we are on a PR, checkout the merge commit sha, else checkout the main branch
          ref: ${{ fromJSON(steps.pr.outputs.result).merge_commit_sha || 'refs/heads/main'}}

      - name: "setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: 2.7

      - name: "bundle lock"
        run: bundle lock

      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "download"
        run: curl -o wss-unified-agent.jar https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar

      - name: "scan"
        run: java -jar wss-unified-agent.jar
        env:
          WS_APIKEY: ${{ secrets.MEND_API_KEY }}
          WS_WSS_URL: https://saas-eu.whitesourcesoftware.com/agent
          WS_USERKEY: ${{ secrets.MEND_TOKEN }}
          WS_PRODUCTNAME: "DevX"
          WS_PROJECTNAME: ${{  github.event.repository.name }}
